/* CS261- Assignment 1 - Q.1*/
/* Name: Jordan Bayles
 * Date:
 * Solution description: Random IDs are generated by instantiating
   an array with integers over the desired range, and randomly swapping
   elements using rand() until sufficient entropy is created. Students
   are allocated, content generated and displayed, and then deallocated.
 */

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define NUM_STUDENTS 10
#define MAX_SCORE 100

struct student
{
    int id;
    int score;
};

/*
   Function: allocate uses malloc to allocate sufficient space for a struct
             array of students with size NUM_STUDENTS
   Pre-cond: none.
   Pst-cond: A pointer to an array of students size NUM_STUDENTS is returned.
*/
struct student* allocate()
{
    /*Allocate memory for ten students*/
    struct student *mem_students = (struct student *)malloc(
                                                       NUM_STUDENTS * sizeof( struct student ) );
    /*return the pointer*/
    return mem_students;
}


/*
   Function: Generate fills the students struct array with valid IDs and score values.
             Scores are randomly selected from [0, MAX_SCORE], and IDs from [1, NUM_STUDENTS].
   Pre-cond: Students must be previously allocated (such as through use of allocate()
   Pst-cond: Students contain valid, randomized data.
*/
void generate(struct student* students)
{
    /* method here: select numbers 1 - 10, and use rand to shuffle them. */
    int ids[ NUM_STUDENTS ];
    int new_slot;
    int temp_id;

    /* put initial values into ids */
    for( int i = 0; i < NUM_STUDENTS; ++i )
        {
        /* Offset by one, as IDs start at 1 but array at 0 */
        ids[ i ] = i + 1;
        }

    /* use rand() to shuffle the numbers */
    for( int i = 0; i < NUM_STUDENTS; ++i )
        {
        /* Get the new position of this slot */
        new_slot = rand() % NUM_STUDENTS;

        /* Swap the value in new_slot with the current slot i */
        temp_id = ids[ new_slot ];
        ids[ new_slot ] = ids[ i ];
        ids[ i ] = temp_id;
        }

    /* Assign IDs, scores */
    for( int i = 0; i < NUM_STUDENTS; ++i )
        {
        students[ i ].id = ids[ i ];
        students[ i ].score = rand() % MAX_SCORE;
        }
}

/*
   Function: The data contained in the passed in struct array is printed out.
   Pre-cond: As id and score are not pointers (and thus instantiated to valid
             data), as long as students has been allocated there is no error.
             Data should be generated before outputting it, however.
   Pst-cond: No variable modification, data piped through stdout.
*/
void output(struct student* students)
{
    for( int i = 0; i < NUM_STUDENTS; ++i )
        {
        printf( "%d %d\n", students[ i ].id, students[ i ].score );
        }
}

/*
   Function: Summary prints key characteristics for the student array,
             including the min, max, and average scores.
   Pre-cond: Students should have valid scores and associated IDs
   Pst-cond: Calculated scores outputted through stdout.
*/
void summary(struct student* students)
{
    /*Set minimum and maximum values to worst case score*/
    int min = MAX_SCORE;
    int max = 0;
    int average = 0;

    for( int i = 0; i < NUM_STUDENTS; ++i )
        {
        /* Found new minimum score */
        if( students[ i ].score < min )
            {
            min = students[ i ].score;
            }
        /* Found new maximum score */
        else if( students[ i ].score > max )
            {
            max = students[ i ].score;
            }

        average += students[ i ].score;
        }

    average = average / NUM_STUDENTS;
    printf( "min: %d, max: %d, average: %d\n", min, max, average );
}

/*
   Function: Deallocate frees the memory of a student struct array
   Pre-cond: Passed in struct array should be allocated.
   Pst-cond: Memory is free, and stud deallocated.
*/
void deallocate(struct student* stud)
{
    /*Deallocate memory from stud*/
    free( stud );
}

/*
   Function: main() seeds rand() using time since epoch, and calls
             helper functions
   Pre-cond: none.
   Pst-cond: none (deallocated).
*/
int main()
{
    struct student* stud = NULL;

    /* seed random function (should only be done 1x per program, so in main) */
    srand( time( NULL ) );

    /*call allocate*/
    stud = allocate();

    /*call generate*/
    generate( stud );

    /*call output*/
    output( stud );

    /*call summary*/
    summary( stud );

    /*call deallocate*/
    deallocate( stud );

    return 0;
}
